# Generated by Django 6.0.4 on 2026-04-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('last_transactions_sync_cursor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_account_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(max_length=100)),
                ('account_subtype', models.CharField(blank=True, max_length=100)),
                ('mask', models.CharField(blank=True, max_length=16)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.plaiditem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_transaction_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('pending', models.BooleanField(default=False)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('category_primary', models.CharField(blank=True, max_length=255)),
                ('category_detailed', models.CharField(blank=True, max_length=255)),
                ('payment_channel', models.CharField(blank=True, max_length=100)),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.account')),
            ],
            options={
                'ordering': ['-date', '-updated_at'],
            },
        ),
    ]
