# Generated by Django 6.0.4 on 2026-04-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='last_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='last_sync_success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
